services:
  credit-distributor:
    environment:
      MAINNET_ENDPOINT: ${MAINNET_ENDPOINT}
      SCHAIN_ENDPOINT: ${SCHAIN_ENDPOINT}
      MAINNET_CONTRACTS: ${MAINNET_CONTRACTS}
      SCHAIN_CONTRACTS: ${SCHAIN_CONTRACTS}
      SCHAIN_NAME: ${SCHAIN_NAME}
      FROM_BLOCK: ${FROM_BLOCK}
      ETH_PRIVATE_KEY: ${ETH_PRIVATE_KEY}
    image: credit-distributor:latest
    container_name: credit_distributor
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
    restart: unless-stopped
